---
title: zSpark
email: z_Spark@163.com
description: 任何正常智商的成熟人类个体都能无障碍理解全部的人类智慧。
url: http://www.zspark.net
baseurl: "/"
github_username: zSpark
blank: "&nbsp; &nbsp; "
b: "&nbsp; &nbsp; "
assetsurl: "/assets/"
imgurl: "/assets/img/"
swfurl: "/assets/swf/"
posturl: "/post/"
libsurl: "/libs/"
exclude:
- exclude
- webgl/mongoose-free-6.4.exe
- ".git"
openFeed: false
highlighter: pygments
markdown: kramdown
permalink: "/post/:categories/:title.html"
gems:
- jekyll-admin
version: 0.8.1
