# Site settings
title: "Jerry Chaos"
email: "z_Spark@163.com"
description: "任何正常智商的成熟人类个体都能无障碍理解人类全部的智慧。"
baseurl:  # the subpath of your site, e.g. /blog
url: "http://www.zspark.net" # the base hostname & protocol for your site
github_username:  "zSpark"

#格式
blank: "&nbsp; &nbsp; "
b: "&nbsp; &nbsp; "
#paginate: 3
#paginate_path: "page:num"

#目录配置
assetsurl: "/assets/"
imgurl: "/assets/img/"
swfurl: "/assets/swf/"
posturl: "/post/"
libsurl: "/libs/"

#屏蔽目录或文件
exclude: [exclude]

#custom value;
openFeed: true

# Build settings
highlighter: pygments 
markdown: kramdown
permalink: /post/:categories/:title.html




